### ISSUE TITLE
Scripts don't start on click

### ISSUE THREAD

**Issue by adrianrdzv** [hassio-addons/addon-control-panel#7]
# Problem

Script is shown in Control Panel but nothing happens on click

## Expected behavior

Script should be triggered on click

## Actual behavior

Script does not get triggered

## Steps to reproduce

I have the following switch:
```
switch:
  - platform: rpi_gpio
    ports:
      2: Garage
```
And the following script:
```
garage_door:
  alias: Toogle garage door
  sequence:
  - data:
      entity_id: switch.garage
    service: switch.turn_on
  - delay: 
      milliseconds: 500
  - data:
      entity_id: switch.garage
    service: switch.turn_off
```
Both switch and script appear on the control panel. The switch works fine, the script doesn't. The script works fine through Home assistant's Overview page.
